marketing/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required as lr

from marketing.views import CrearPromocion, ListarHome, ViewMenu, ViewPromo, EnviarCorreo, \
							RegistrarCorreo, ListarRecetaImagen, EditarImagenReceta, \
							DetallePromocion, DetalleProducto


urlpatterns = [
    url(r'^sobre_nosotros/', RegistrarCorreo.as_view(), name = 'acerca_de'),
    url(r'^recetas/', lr(ListarRecetaImagen.as_view()), name='receta_listar'),
    url(r'^receta/editar/(?P<pk>\d+)$', lr(EditarImagenReceta.as_view()), name='receta_editar'),
    url(r'^nueva_promo', lr(CrearPromocion.as_view()), name='crear_promocion'),
    url(r'^home/',ListarHome.as_view(), name='index'),
    url(r'^menu/',ViewMenu.as_view(), name='menu'),
    url(r'^promocion/',ViewPromo.as_view(), name='promo'),
    url(r'^sendmail/',EnviarCorreo, name='mailing'),
    url(r'^detalle/(?P<pk>\d+)/$', DetallePromocion.as_view(), name='detalle_promocion'),
    url(r'^detalle/receta/(?P<pk>\d+)/$', DetalleProducto.as_view(), name='detalle_producto'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

proyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('marketing.urls', namespace='promocion')),
    url(r'^accounts/login/', login, {'template_name':'home/login.html'}, name = 'login'),
    url(r'^logout/', logout, {'next_page': 'promocion:index'}, name='logout'),
]

marketing/models.py
from django.db import models

# Create your models here.

class Receta(models.Model):
    nombre = models.CharField(max_length=100, blank = False, null = False)
    precio = models.FloatField()
    existencias = models.IntegerField()
    imagen = models.ImageField(upload_to='recetas', blank=False, null=False)
    descripcion = models.TextField(max_length=200, blank= True, null=True)
    class Meta:
        db_table = 'Receta'

    def __str__(self):
        return self.nombre

class Promocion(models.Model):
    nombre = models.CharField(max_length=100, blank=False, null=False)
    precio = models.FloatField()
    descuento = models.FloatField()
    imagen = models.ImageField(upload_to='promociones', blank=False, null=False)
    recetas = models.ManyToManyField(Receta, blank=False)
    descripcion = models.TextField(max_length=200, blank = True, null=True)
    class Meta:
        db_table = 'Promocion'

    def __str__(self):
        return self.nombre

class Suscriptores(models.Model):
    nombre = models.CharField(max_length=100, null=True, blank=True)
    correo = models.EmailField(max_length=100,null=False, blank=False)
    class Meta:
        db_table = 'Suscriptores'

marketing/forms.py
# -*- coding: utf-8 -*-
u''

from django import forms
from marketing.models import Promocion, Suscriptores, Receta

class PromoForm(forms.ModelForm):
    class Meta:
        model = Promocion
        fields = '__all__'

class CorreoForm(forms.ModelForm):
    class Meta:
        model = Suscriptores
        fields = '__all__'

class RecetaForm(forms.ModelForm):
    class Meta:
        model = Receta
        fields = [
            'imagen',
            'descripcion',
        ]

marketing/views.py
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
import datetime
import os
from django.conf import settings
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.core.urlresolvers import reverse_lazy

from marketing.forms import PromoForm, CorreoForm, RecetaForm
from .models import Promocion, Receta, Suscriptores

# Create your views here.

meses = [
    ' ', 'Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre', 'Diciembre',
]

class CrearPromocion(CreateView):
    form_class = PromoForm
    template_name = 'marketing/promo_form.html'
    success_url = reverse_lazy('promocion:promo')

class RegistrarCorreo(CreateView):
    form_class = CorreoForm
    template_name = 'marketing/contacto.html'
    success_url = reverse_lazy('promocion:acerca_de')

def EnviarCorreo(request):
    asunto = 'Nuevas promociones BLISS'
    promociones = Promocion.objects.all()[:2]
    automensaje = 'visita nuestros restaurantes este mes de ' + meses[datetime.datetime.now().month] + ' y prueba nuestras promociones: \n\n'
    for promo in promociones:
        automensaje = automensaje + promo.nombre + ':\n' + promo.descripcion + '\n' + 'a un precio super especial de:\nQ'+ str(promo.precio) +'\n\n'
    suscriptors = Suscriptores.objects.all()
    for suscriptor in suscriptors:
        mensaje = 'Hola ' + suscriptor.nombre + '!\n' + automensaje
        mail = EmailMessage(asunto, mensaje, to = [suscriptor.correo])
        mail.attach_file(os.path.join(settings.MEDIA_ROOT, promociones[0].imagen.path))
        mail.attach_file(os.path.join(settings.MEDIA_ROOT, promociones[1].imagen.path))
        mail.send()
        mensaje = automensaje
    return redirect('promocion:index')
    return render(request,'home/index.html')

class ListarHome(ListView):
	template_name='home/index.html'
	model = Receta

	def get_context_data(self, **kwargs):
		context = super(ListarHome, self).get_context_data(**kwargs)
		context['promocion'] = Promocion.objects.all()[:3]
		return context

class ListarRecetaImagen(ListView):
    template_name='marketing/imagenes_recetas.html'
    model = Receta
    paginate_by = 3

class ViewMenu(ListView):
	template_name='marketing/menu.html'
	model = Receta

class EditarImagenReceta(UpdateView):
    model = Receta
    form_class = RecetaForm
    template_name = 'marketing/receta_form.html'
    success_url = reverse_lazy('promocion:receta_listar')

class ViewPromo(ListView):
	template_name='marketing/promocion.html'
	model = Promocion

class DetallePromocion(DetailView):
    template_name = 'marketing/detalle_promo.html'
    model = Promocion

    def get_context_data(self, **kwargs):
        context = super(DetallePromocion, self).get_context_data(**kwargs)
        context['real'] = context['object'].precio - context['object'].descuento
        context['promocion'] = Promocion.objects.exclude(id = context['object'].id)[:3]
        return context

class DetalleProducto(DetailView):
    model = Receta
    template_name = 'marketing/detalle_producto.html'

    def get_context_data(self, **kwargs):
        context = super(DetalleProducto, self).get_context_data(**kwargs)
        context['productos'] = Receta.objects.exclude(id = context['object'].id)[:3]
        return context

templates/home/index.html
{% load staticfiles%}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Home</title>
<meta charset="utf-8">
<meta name = "format-detection" content = "telephone=no" />
<link rel="icon" href=" {%static 'images/favicon.ico'%}">
<link rel="shortcut icon" href="{% static 'images/favicon.ico'%}" />
<link rel="stylesheet" href="{% static 'css/stuck.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
<link rel="stylesheet" href="{% static 'css/touchTouch.css'%}">
<script src="{% static 'js/jquery.js'%}"></script>
<script src="{% static 'js/jquery-migrate-1.1.1.js'%}"></script>
<script src="{% static 'js/script.js'%}"></script>
<script src="{% static 'js/superfish.js'%}"></script>
<script src="{% static 'js/jquery.equalheights.js'%}"></script>
<script src="{% static 'js/jquery.mobilemenu.js'%}"></script>
<script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
<script src="{% static 'js/tmStickUp.js'%}"></script>
<script src="{% static 'js/jquery.ui.totop.js'%}"></script>
<script src="{% static 'js/touchTouch.jquery.js'%}"></script>

<script>
 $(document).ready(function(){

  $().UItoTop({ easingType: 'easeOutQuart' });
  $('#stuck_container').tmStickUp({});
  $('.gallery .gall_item').touchTouch();

  });
</script>
<!--[if lt IE 9]>
 <div style=' clear: both; text-align:center; position: relative;'>
   <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
     <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
   </a>
</div>
<script src="js/html5shiv.js"></script>
<link rel="stylesheet" media="screen" href="css/ie.css">


<![endif]-->
</head>

<body class="page1" id="top">
<!--==============================
              header
=================================-->
<header>
<!--==============================
            Stuck menu
=================================-->
  <section id="stuck_container">
    <div class="container">
      <div class="row">
        <div class="grid_12">
        <h1>
          <a href="{%url 'promocion:index'%}" alt="Logo alt">
            <img src="{%static 'images/logo.png'%}">
          </a>
        </h1>
          <div class="navigation">
            <nav>
              <ul class="sf-menu">
                <li><a href="{%url 'promocion:index'%}">Inicio</a></li>
                {% if user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Productos<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{%url 'promocion:menu'%}">Menu</a></li>
                    <li><a href="{%url 'promocion:promo'%}">Promociones</a></li>
                  </ul>
                </li>
                <li class="dropdown" style="width:100px;">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Operaciones<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{%url 'promocion:crear_promocion'%}">Crear promoción</a></li>
                    <li><a href="{%url 'promocion:receta_listar'%}">Imagenes recetas</a></li>
                    <li><a href="{% url 'promocion:mailing' %}">Enviar correos</a></li>
                  </ul>
                </li>
                <li><a href="{% url 'logout' %}">Salir</a></li>
                {% else %}
                  <li><a href="{%url 'promocion:menu'%}">Menu</a></li>
                  <li><a href="{%url 'promocion:promo'%}">Promociones</a></li>
                  <li><a href="{% url 'promocion:acerca_de' %}">Acerca de</a></li>
                {% endif %}
             </ul>
            </nav>
            <div class="clear"></div>
          </div>
        </div>
      </div>
    </div>
  </section>
</header>

<!--=====================
          Content
======================-->
{% block content%}


<!-- Inicio de productos -->
<section class="content">
  <div class="container">
    <div class="row">


      <div class="grid_4">
        <div class="banner">
      <div class="gall_block">
          <img src="{%static 'images/page1_img1.jpg'%}" alt="">
          <div class="bann_capt ">
            <div class="maxheight">
              <img src="{%static 'images/icon1.png'%}" alt="">
              <div class="bann_title">La mejor comida italiana, donde no se podra encontrar
              en otra parte</div>

            </div>
          </div>
        </div>
     </div>
      </div>
      <div class="grid_4">
        <div class="banner">
      <div class="gall_block">
          <div class="bann_capt  bn__1">
            <div class="maxheight">
              <img src="{%static 'images/icon2.png'%}" alt="">
              <div class="bann_title">Ademas de ofrecer comida variada, ofrecemos un gran servicio</div>

            </div>
          </div>
          <img src="{%static 'images/page1_img2.jpg'%}" alt="">
        </div>
    </div>
      </div>
      <div class="grid_4">
        <div class="banner ">
      <div class="gall_block">
          <img src="{%static 'images/page1_img3.jpg'%}" alt="">
          <div class="bann_capt  bn__2">
            <div class="maxheight">
              <img src="{%static 'images/icon3.png'%}" alt="">
              <div class="bann_title">En cuanto a ofertas se refieren, nuestro restaurante, da las mejores
              promociones</div>

            </div>
          </div>
      </div>
        </div>
      </div>
      <div class="grid_12">
        <h2>Productos </h2>
      </div>

    {%for producto in object_list%}
        <div class="grid_4">
          <div class="banner ">
            <div class="gall_block">
              <img src="{{producto.imagen.url}}" alt="" width= '370px' height= '305px'>
              <div class="bann_capt  bn__1">
                <div class="maxheight">
                  <img src="{%static 'images/icon1.png'%}" alt="">
                    <div class="bann_title">{{producto.nombre}} <br> {{producto.descripcion}}</div>
                </div>
              </div>
            </div>
        </div>
      </div>
    {%endfor%}

    <div class="grid_12">
      <h2>Promociones </h2>
    </div>

    {%for promo in promocion%}
        <div class="grid_4">
          <div class="banner ">
            <div class="gall_block">
              <img src="{{promo.imagen.url}}" alt="" width= '370px' height= '305px'>
              <div class="bann_capt  bn__1">
                <div class="maxheight">
                  <img src="{%static 'images/icon1.png'%}" alt="">
                    <div class="bann_title">{{promo.nombre}} <br> {{promo.descripcion}}</div>
                </div>
              </div>
            </div>
        </div>
      </div>
    {%endfor%}


    <div class="grid_12">
    </div>


<!-- Fin de productos y promociones -->

      <div class="grid_12">
        <div class="box">
          <div class="row">
            <div class="grid_5 preffix_1">
              <h2>Welcome</h2>
              <p>Post about this <strong class="color1"><a href="http://blog.templatemonster.com/free-website-templates/" rel="nofollow">freebie</a></strong> will tell all you need to know about it. Need a good choice of <strong class="color1"><a href="http://www.templatemonster.com/properties/topic/food-restaurant/" rel="nofollow">themes</a></strong>? Visit TemplateMonster’s website.</p>
              Aliquam nibh e,estas id dictum a, commodo. Praesent faucibus malesuada faucibusonec laeet metus id laoreet malesuadarem ipsum dolor sit <br>
            </div>
            <div class="grid_5">
              <h2>Feel the Savor of Life</h2>
              Dervamus at magna non nunc tristique rhoncus. Aliquam nibh ante, egestas id dictum a, commodo. Praesent faucibus malesuada ucibus. Donec laeet metus id laoreet malesuadarem ipsum dosit ametctetur adipiscing elit. Nullam consectetur orci sed nulla facilisis consequat. Curabitur vel lorem sit amet nulla ullamcorper fermentum. <br>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

{% endblock%}
<!--==============================
              footer
=================================-->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="grid_12">
        <div class="socials">
          <a href="#" class="fa fa-twitter"></a>
          <a href="#" class="fa fa-facebook"></a>
          <a href="#" class="fa fa-google-plus"></a>
          <a href="{% url 'login' %}" class="fa fa-pinterest">Entrar</a>
        </div>
          <center>
          </center>
        <div class="copyright">
          <span class="brand">Restaurante </span> &copy; <span id="copyright-year"></span> |  <div>Website designed by Kevin y Alexander</div>
        </div>
      </div>
    </div>
  </div>
</footer>
</body>

</html>

templates/marketing/detalle_producto.html
{% extends 'home/index.html'%}

{%block content%}
<section class="content"><div class="ic"></div>
  <div class="container">
    <div class="row">

      <div class="grid_7">
        <h2>{{object.nombre}}</h2>
          <img src="{{object.imagen.url}}" alt="" class=" fleft" width="100px" height="150px">
          <div class="extra_wrapper">
          <div class="bq_title color1">Descripcion</div>
       		<div style="color:#101223"><p>{{object.descripcion}}</p>
          <h5>Precio</h5>
          {{object.precio}}
          </div> 
          </div>
        
      </div>

      <div class="grid_4 preffix_1">
        <h2>Otros</h2>
        {% for producto in productos%}
        <div class="block3">
          <img src="{{producto.imagen.url}}" width="220px" height="120px" alt="" class="img_inner">
          <div class="extra_wrapper">
            <div class="text1 color1">
              <a href="{% url 'promocion:detalle_producto' producto.id%}">{{producto.nombre}}</a>
            </div>
            <div style="color:#101223">{{producto.descripcion}}<a href="#" class="color1">[...]</a></div>
          </div>
        </div>
        {% endfor%}
      </div>
      </div>
      </div>
      </section>

{%endblock%}

templates/marketing/detalle_promo.html
{% extends 'home/index.html'%}

{%block content%}
<section class="content"><div class="ic"></div>
  <div class="container">
    <div class="row">

      <div class="grid_7">
        <h2>{{object.nombre}}</h2>
          <img src="{{object.imagen.url}}" alt="" class=" fleft" width="100px" height="150px">
          <div class="extra_wrapper">
          <div class="bq_title color1">Descripcion</div>
          <div style="color:#101223"><p>{{object.descripcion}}</p>
          <h5>Precio</h5>
          {{real}}
          </div>
          </div>
        
      </div>

      <div class="grid_4 preffix_1">
        <h2>Otras Promociones</h2>
        {% for promo in promocion%}
        <div class="block3">
          <img src="{{promo.imagen.url}}" width="220px" height="120px" alt="" class="img_inner">
          <div class="extra_wrapper">
            <div class="text1 color1">
              <a href="{% url 'promocion:detalle_promocion' promo.id%}">{{promo.nombre}}</a>
              </div>
              <div style="color:#101223">{{promo.descripcion}}<a href="#" class="color1">[...]</a></div>
          </div>
        </div>
        {% endfor%}
      </div>
 	</div>
 	</div>
 	</section>

{%endblock%}

templates/marketing/imagenes_recetas.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name = "format-detection" content = "telephone=no" />
    <link rel="icon" href=" {% static 'images/favicon.ico' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}" />
    <link rel="stylesheet" href="{% static 'css/stuck.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/touchTouch.css'%}">
    <script src="{% static 'js/jquery.js'%}"></script>
    <script src="{% static 'js/jquery-migrate-1.1.1.js'%}"></script>
    <script src="{% static 'js/script.js'%}"></script>
    <script src="{% static 'js/superfish.js'%}"></script>
    <script src="{% static 'js/jquery.equalheights.js'%}"></script>
    <script src="{% static 'js/jquery.mobilemenu.js'%}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
    <script src="{% static 'js/tmStickUp.js'%}"></script>
    <script src="{% static 'js/jquery.ui.totop.js'%}"></script>
    <script src="{% static 'js/touchTouch.jquery.js'%}"></script>

    <script>
     $(document).ready(function(){

      $().UItoTop({ easingType: 'easeOutQuart' });
      $('#stuck_container').tmStickUp({});
      $('.gallery .gall_item').touchTouch();

      });
    </script>
    <style>
    table {
      border: 1px solid black;
      width: 50%;
    }

    thead, td {
      border: 1px solid black;
      text-align: center;
      color: black;
      padding: 8px;
      vertical-align: middle;
    }

    tr:nth-child(even){background-color: #C9FFC9;}

    thead {
      background-color: #4CAF50;
    }

    body{
      background-color: white;
    }

    .fk{
      color: white;
      background-color: #663399;
      padding: 4px 30px;
      cursor: pointer;
      margin: 10px;
      text-align:center;
    }

    </style>
  </head>
  <body>
    <header>
    <!--==============================
                Stuck menu
    =================================-->
      <section id="stuck_container">
        <div class="container">
          <div class="row">
            <div class="grid_12">
            <h1>
              <a href="{%url 'promocion:index'%}" alt="Logo alt">
                <img src="{%static 'images/logo.png'%}">
              </a>
            </h1>
            <div class="navigation">
              <nav>
                <ul class="sf-menu">
                  <li><a href="{%url 'promocion:index'%}">Inicio</a></li>
                  <li class="dropdown" style="width:70px;">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Listar<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="{%url 'promocion:menu'%}">Menu</a></li>
                      <li><a href="{%url 'promocion:promo'%}">Promociones</a></li>
                    </ul>
                  </li>
                  <li class="dropdown" style="width:100px;">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Operaciones<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="{%url 'promocion:crear_promocion'%}">Crear promoción</a></li>
                      <li><a href="{%url 'promocion:receta_listar'%}">Imagenes recetas</a></li>
                      <li><a href="{% url 'promocion:mailing' %}">Enviar correos</a></li>
                    </ul>
                  </li>
                  <li><a href="{% url 'logout' %}">Salir</a></li>
                </ul>
              </nav>
              <div class="clear"></div>
            </div>
            </div>
          </div>
        </div>
      </section>
    </header>
    <center>
  <table class="table table-bordered">
    <thead>
      <tr>
        <td>Imagen</td>
        <td>Receta</td>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
      {% for receta in object_list %}
      <tr>
        <td>
          <p>
            <a href="{{ receta.imagen.url }}"><img src="{{ receta.imagen.url }}" style="width:150px;height:140px;"></a>
          </p>
          <a href="{%url 'promocion:receta_editar' receta.id %}" style="text-decoration: underline;">actualizar</a>
        </td>
        <td>{{ receta.nombre }}</td>
      </tr>
      {% endfor %}
      {% else %}
      <h3>No hay registros de recetas!!!</h3>
      {% endif %}
    </tbody>
  </table>
  <br>
  <br>
<div class="pager" style="display: flex;justify-content: center;">
    {% if page_obj.has_previous %}
      <a class="fk" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
    {% endif %}
    {% if page_obj.has_next %}
      <a class="fk" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
      {% endif %}
</div>
    </center>
  </body>
</html>

templates/marketing/promo_form.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Nueva Promoción</title>
  <meta name = "format-detection" content = "telephone=no" />
  <link rel="icon" href=" {% static 'images/favicon.ico' %}">
  <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}" />
  <link rel="stylesheet" href="{% static 'css/stuck.css'%}">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="{% static 'css/touchTouch.css'%}">
  <script src="{% static 'js/jquery.js'%}"></script>
  <script src="{% static 'js/jquery-migrate-1.1.1.js'%}"></script>
  <script src="{% static 'js/script.js'%}"></script>
  <script src="{% static 'js/superfish.js'%}"></script>
  <script src="{% static 'js/jquery.equalheights.js'%}"></script>
  <script src="{% static 'js/jquery.mobilemenu.js'%}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
  <script src="{% static 'js/tmStickUp.js'%}"></script>
  <script src="{% static 'js/jquery.ui.totop.js'%}"></script>
  <script src="{% static 'js/touchTouch.jquery.js'%}"></script>

  <script>
   $(document).ready(function(){

    $().UItoTop({ easingType: 'easeOutQuart' });
    $('#stuck_container').tmStickUp({});
    $('.gallery .gall_item').touchTouch();

    });
  </script>
  <style>
  table {
    width: 50%;
  }

  td {
    text-align: center;
    color: black;
    padding: 8px;
    vertical-align: middle;
  }

  tr:nth-child(even){background-color: #E8D9F7}

  .btn {
    background-color: #663399;
    border: none;
    color: white;
    padding: 8px 30px;
    text-align: center;
    text-decoration: none;
    font-size: 14px;
    margin: 4px 2px;
    cursor: pointer;
  }
  body{
    background-color: white;
  }
  .dk{
    text-align: left;
    padding: 8px;
  }
  </style>
</head>
<body>
  <header>
  <!--==============================
              Stuck menu
  =================================-->
    <section id="stuck_container">
      <div class="container">
        <div class="row">
          <div class="grid_12">
          <h1>
            <a href="{%url 'promocion:index'%}" alt="Logo alt">
              <img src="{%static 'images/logo.png'%}">
            </a>
          </h1>
          <div class="navigation">
            <nav>
              <ul class="sf-menu">
                <li><a href="{%url 'promocion:index'%}">Inicio</a></li>
                <li class="dropdown" style="width:70px;">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Listar<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{%url 'promocion:menu'%}">Menu</a></li>
                    <li><a href="{%url 'promocion:promo'%}">Promociones</a></li>
                  </ul>
                </li>
                <li class="dropdown" style="width:100px;">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Operaciones<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{%url 'promocion:crear_promocion'%}">Crear promoción</a></li>
                    <li><a href="{%url 'promocion:receta_listar'%}">Imagenes recetas</a></li>
                    <li><a href="{% url 'promocion:mailing' %}">Enviar correos</a></li>
                  </ul>
                </li>
                <li><a href="{% url 'logout' %}">Salir</a></li>
              </ul>
            </nav>
            <div class="clear"></div>
          </div>
          </div>
        </div>
      </div>
    </section>
  </header>
  <br>
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <center>
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td>{{ form.nombre.label }}:</td>
          <td class="dk">{{ form.nombre }}</td>
        </tr>
        <tr>
          <td>{{ form.precio.label }}:</td>
          <td class="dk">{{ form.precio }}</td>
        </tr>
        <tr>
          <td>{{ form.descuento.label }}:</td>
          <td class="dk">{{ form.descuento }}</td>
        </tr>
        <tr>
          <td>{{ form.imagen.label }}:</td>
          <td class="dk">{{ form.imagen }}</td>
        </tr>
        <tr>
          <td>{{ form.recetas.label }}:</td>
          <td class="dk">{{ form.recetas }}</td>
        </tr>
        <tr>
          <td>{{ form.descripcion.label }}:</td>
          <td class="dk">{{ form.descripcion }}</td>
        </tr>
      </tbody>
    </table>
    <br>
      <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
          <button class = "btn btn-primary" type="submit" name="button">Guardar</button>
        </div>
      </div>
  </center>
</form>
</body>
</html>